name: NOVI CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # Alleen als build-and-test slaagt
  push-to-dockerhub:
    # Deze job 'heeft nodig' (wacht op) de vorige job
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Stap 1: Login bij Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Stap 2: Bouw en push de Docker image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: . # Zoek de Dockerfile hier
          push: true # Push 'm ook echt
          # Geef de image een naam
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/novi-demo-app:latest
